### ISSUE TITLE
How to work with datetime fields in a update transaction?

### ISSUE THREAD

**Issue by NatanVieira** [alexwiese/EntityFrameworkCore.OpenEdge#20]
Hello @alexwiese,
First at all, your code is help me too much.
I'm trying to add a record, but a datetime field is crashing code execution, without the field the code execute perfectly, but with it doesn't and return this message: 
ERROR [42522] [DataDirect][ODBC Progress OpenEdge Wire Protocol driver][OPENEDGE]Column "TIMESTAMP" cannot be found or is not specified for query. (13865).
May you help me? 

Follow the link with an example code and the table's .df.
https://github.com/NatanVieira/ErrorTimestamp.git

thanks.

**Comment by alexwiese** [comment]
hi @NatanVieira what version of EntityFrameworkCore.OpenEdge are you using? 

You could check issue #15 or try one of the RC versions.

**Comment by NatanVieira** [comment]
Hi, @alexwiese, thanks for the quick feedback.
Sorry I didn't see the other issues, I'm new to both git and C # development, I tried the issue #15 solution, but I had the same problem.
The library version is 1.0.11.
Thank you for your help.
